services:
  db:
    image: postgres:13
    env_file:
      - .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./kittigram_backend
    env_file:
      - .env.example
    depends_on:
      - db
    volumes:
      - static_value:/app/collected_static
      - media_value:/app/media

  frontend:
    build: ./kittigram_frontend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static_value:/static
      - media_value:/media

volumes:
  pg_data:
  static_value:
  media_value: