version: '3.8'

volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./kittigram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./kittigram_frontend
    volumes:
      - frontend_static:/frontend_static

  gateway:
    build: ./gateway
    volumes:
      - static:/static
      - media:/media
      - frontend_static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend