# Generated by Django 5.1.1 on 2026-05-05 11:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('cat_created', 'Создание кота'), ('cat_updated', 'Редактирование кота'), ('achievement_added', 'Добавление достижения'), ('image_uploaded', 'Добавление изображения')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('points', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('is_active', models.BooleanField(default=True)),
                ('once_per_object', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило начисления XP',
                'verbose_name_plural': 'Правила начисления XP',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль XP',
                'verbose_name_plural': 'Профили XP',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('points', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cats.xpactionrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие XP',
                'verbose_name_plural': 'События XP',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'action'], name='cats_xpeven_user_id_f95353_idx'), models.Index(fields=['object_id'], name='cats_xpeven_object__52204b_idx')],
            },
        ),
    ]
