# Generated by Django 5.1.1 on 2026-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_xpactionrule_profile_xpevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpactionrule',
            name='code',
            field=models.CharField(choices=[('cat_created', 'Создание кота'), ('cat_updated', 'Редактирование кота'), ('achievement_added', 'Добавление достижения'), ('image_uploaded', 'Добавление изображения'), ('manual_grant', 'Ручное начисление XP администратором')], max_length=32, unique=True),
        ),
    ]
